Repository cloudfoundry/bosh-cli, pull requests merged in 2020-06, with the labels that each got.

#556 Prefix exported release file with the provided jobs
  cmd/export_release.go
  cmd/export_release_test.go
Labels: scheduled

#560 Added support for showing in_progress event updates
  ui/task/event.go
  ui/task/event_test.go
  ui/task/reporter.go
  ui/task/reporter_test.go
Labels: unscheduled

#559 Add --fix-releases flag to the deploy command
  cmd/cmdfakes/fake_release_uploader.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/opts/opts.go
  cmd/opts/opts_test.go
  cmd/release_manager.go
  cmd/release_manager_test.go
Labels: in progress
